version: 2

updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: tuesday
      time: "09:00"
      timezone: Europe/Vilnius
    open-pull-requests-limit: 5
    assignees:
      - MatasMac
    commit-message:
      prefix: build
      prefix-development: build
      include: scope
    groups:
      docusaurus-minor-and-patch:
        patterns:
          - "@docusaurus/*"
        update-types:
          - minor
          - patch
      npm-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: wednesday
      time: "09:00"
      timezone: Europe/Vilnius
    open-pull-requests-limit: 3
    assignees:
      - KirilKurkianec
    commit-message:
      prefix: ci
      include: scope
    groups:
      github-actions-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
